version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000" # Map host port 5001 to container port 5000
    environment:
      - FLASK_ENV=production # Set to production
    restart: unless-stopped # Ensure the service restarts if it stops unexpectedly
