version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:5000" # Map host port 80 to container port 5000 for standard HTTP
    environment:
      - FLASK_ENV=production # Set to production
    restart: unless-stopped # Ensure the service restarts if it stops unexpectedly
